name: publish to nuget
on:
  push:
    tags:        
      - '*'
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: publish on version change
        id: publish_nuget
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/KillDNS.CaptchaSolver.Handlers.WinForms.Common.csproj
          PACKAGE_NAME: KillDNS.CaptchaSolver.Handlers.WinForms.Common
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}